---

- hosts: localhost

  roles: 
    - ansible-set-hostname
    - ansible-motioneye

  tasks:

    - name: "Ansible-pull is managing this system" 
      file: 
        name: "iot1.sud0.com.yml" 
        state: touch 
