---

- hosts: localhost

  roles:
    - role-ansible-pull
    - role-auto-apply-updates
    - role-yum-google-chrome
    - role-centos7-multimedia

  tasks:

    - name: "Install Deja-Dup"
      yum:
        name: "{{ item }}"
        state: installed
        disable_gpg_check: yes
      with_items:
        - https://kojipkgs.fedoraproject.org/packages/python-cloudfiles/1.7.11/1.el7/noarch/python-cloudfiles-1.7.11-1.el7.noarch.rpm
        - https://kojipkgs.fedoraproject.org/packages/deja-dup/34.2/2.el7/x86_64/deja-dup-34.2-2.el7.x86_64.rpm
        - https://kojipkgs.fedoraproject.org//packages/deja-dup/34.2/2.el7/ppc64/deja-dup-nautilus-34.2-2.el7.ppc64.rpm
