--- 

- hosts: localhost

  roles: 
    - role-ansible-pull
    - role-auto-apply-updates
    - role-yum-google-chrome

  tasks: 

    - name: "Install Deja-Dup"
      yum: 
        name: "{{ item }}"
        state: installed
        disable_gpg_check: yes
      with_items:
        - https://kojipkgs.fedoraproject.org//work/tasks/4399/8714399/deja-dup-32.0-3.el7.x86_64.rpm
        - https://kojipkgs.fedoraproject.org//work/tasks/4399/8714399/deja-dup-nautilus-32.0-3.el7.x86_64.rpm
