---

- hosts: localhost

  roles:
    - role-ansible-pull
    - role-auto-apply-updates
    - role-yum-google-chrome
    - role-centos7-multimedia

  tasks:

    - name: "Install Deja-Dup"
      yum:
        name: "{{ item }}"
        state: installed
      with_items:
        - python-cloudfiles
        - deja-dup
        - deja-dup-nautilus
