---

- hosts: localhost

  vars: 
    ansible_pull_url: https://github.com/stenwt/ansible-pull-managed 

  roles: 
    - ansible-set-hostname
    - role-ansible-pull
    - { role: ansible-nextcloud, nextcloud_datadir: /srv/nextcloud } 

  tasks:

    - name: cryptsetup is installed
      dnf:
        name: cryptsetup
        state: present 

    - name: crypttab is configured
      lineinfile:
        dest: /etc/crypttab
        line: "thumb01_crypt /dev/disk/by-uuid/e3f399bb-6a70-4e61-89c9-686684b55aad /root/sda luks" 

    - name: "thumbdrive is mounted" 
      mount:
        path: /srv/nextcloud
        src: /dev/mapper/thumb01_crypt
        fstype: ext4
        state: mounted

    - name: "Ansible-pull is managing this system" 
      file: 
        name: serv01.sud0.com.yml
        state: touch

## dd if=/dev/urandom of=/root/sda bs=1024 count=4
## cryptsetup luksAddKey /dev/sda1 /root/sda
