---

- hosts: localhost

  roles: 
    - ansible-set-hostname
    - role-ansible-pull
    - ansible-nextcloud

  tasks:

    - name: "Ansible-pull is managing this system" 
      file: 
        name: serv01.sud0.com.yml
        state: touch
