---

- hosts: localhost

  vars: 
    ansible_pull_url: https://github.com/stenwt/ansible-pull-managed 

  roles: 
    - ansible-set-hostname
    - role-ansible-pull
    - ansible-nextcloud

  tasks:

    - name: "Ansible-pull is managing this system" 
      file: 
        name: serv01.sud0.com.yml
        state: touch
