---

  - name: Nextcloud requirements are installed
    dnf: 
      name: "{{ item }}"
      state: present
    with_items:
      - php-pdo
      - php-gd 
      - php-json
      - php-mbstring
      - php-xml
      - php-pecl-zip

  - name: Nextcloud from git is installed 
    git: 
      repo: https://github.com/nextcloud/server.git
      dest: /var/www/html/nextcloud
      version: stable12
      
