---

  - name: httpd is installed
    dnf:
      name: httpd
      state: present

  - name: httpd is running
    service:
      name: httpd
      state: started
      enabled: true

  - name: httpd is accessible via firewalld
    firewalld:
      service: "{{ item }}"
      state: enabled
      permanent: true
      immediate: true
    with_items:
      - http
      - https


  - name: httpd has selinux bools set
    seboolean:
      name: "{{ item }}"
      state: yes
      persistent: yes
    with_items:
      - httpd_unified
      - httpd_can_network_connect
