---

  - name: Set DHCP hostname to match hostname
    lineinfile: 
      name: /etc/sysconfig/network
      regexp: '^DHCP_HOSTNAME'
      line: "DHCP_HOSTNAME={{ fqdn | default(ansible_nodename) }}"

  - name: Set hostname if not set 
    command: "hostnamectl set-hostname {{ fqdn |default(ansible_nodename) }}"
    when: fqdn is defined
