---

  - name: Nginx is installed
    dnf:
      name: nginx
      state: present

  - name: Nginx is running
    service:
      name: nginx
      state: started
      enabled: true

  - name: Nginx is accessible via firewalld
    firewalld:
      service: "{{ item }}"
      state: enabled
      permanent: true
      immediate: true
    with_items:
      - http
      - https

  - name: Nginx root is set
    lineinfile:
      path: /etc/nginx/nginx.conf
      regexp: '^( )+root'
      line: '        root /srv/www;'
